### ISSUE TITLE
Few-shot learning

### ISSUE THREAD

**Issue by Gjergj121** [dolev104/neural_congealing#2]
Hi, congrats for the amazing work done in this paper. 

I noticed that some part of this work was based on the Gangealing paper "GAN-Supervised Dense Visual Alignment" by Peebles. I am currently working on the Gangealing paper, and trying to implement few-shot learning in that model, i.e., I want to modify the model that, for example, a gangealing model trained to align cats, can align dogs by giving it a few images of dogs, in a few-shot manner. 
In your models you use the same architecture for the Spatial Transformer as in the Gangealing model, and you train your model with only very few examples. Can it be possible for example to integrate in your model a spatial transformer trained to align cats and train it with a few training samples of dog images to align dogs, doing in this way a sort of "few-shot" learning?

Thank you in advance. :)

**Comment by dolev104** [comment]
Hi @Gjergj121,
 
Thank you for your interest in our work.
In our work we do test time optimization, and the current framework is not built for few-shot learning.
There may be a way to combine GANgealing's method with ours, though. It'd be interesting to try something out :)

Good luck!
